import { nameStackNavigation } from './constante/NameStackNavigation';
import { LoiService } from './services/LoiService';
import {
   storeDataToLocalStorage,
   getDataFromLocalStorage,
   storeFavoriteIdToLocalStorage,
   getFavoriteFromLocalStorage,
   storeStatistiqueToLocalStorage,
} from './storage/asyncStorage';
import {
   ArticleSchema,
   ContenuSchema,
   TypeSchema,
   ThematiqueSchema,
   DoleanceSchema,
   TagSchema,
} from './storage/database';
import { insertOrUpdateToDBFunc } from './storage/querySqlite';
import {
   parseStructureDataForArticle,
   parseStructureDataForContenu,
   filterArticleToListByContenu,
   checkAndsendMailFromLocalDBToAPI,
   parsingTags,
   parseDataArticleLazyLoading,
   parseDataContenuLazyLoading,
   widthPercentageToDP,
   heightPercentageToDP,
   isAloeFile,
   getOverviewData,
   pushNotification,
} from './helper/functionHelpler';

import {
   fetchTypesToApi,
   fetchArticlesToApi,
   fetchArticlesByContenuToApi,
   fetchThematiquesToApi,
   fetchTagsToApi,
   fetchContenusToApi,
   fetchAllDataToLocalDatabase,
   fetchPartialDataForUpdating,
} from './helper/functionFetching';

export {
   nameStackNavigation,
   pushNotification,
   LoiService,
   storeDataToLocalStorage,
   getDataFromLocalStorage,
   storeFavoriteIdToLocalStorage,
   getFavoriteFromLocalStorage,
   storeStatistiqueToLocalStorage,
   ArticleSchema,
   ContenuSchema,
   TypeSchema,
   ThematiqueSchema,
   DoleanceSchema,
   TagSchema,
   insertOrUpdateToDBFunc,
   parseStructureDataForArticle,
   parseStructureDataForContenu,
   checkAndsendMailFromLocalDBToAPI,
   parsingTags,
   fetchTypesToApi,
   fetchTagsToApi,
   parseDataArticleLazyLoading,
   parseDataContenuLazyLoading,
   fetchContenusToApi,
   fetchArticlesToApi,
   fetchArticlesByContenuToApi,
   fetchThematiquesToApi,
   fetchAllDataToLocalDatabase,
   fetchPartialDataForUpdating,
   filterArticleToListByContenu,
   widthPercentageToDP,
   heightPercentageToDP,
   getOverviewData,
   isAloeFile,
};
