export const nameStackNavigation = {
   home: 'Accueil',
   welcome: 'Welcome',
   listArticle: 'ListeArticle',
   listContenu: 'ListeContenu',
   listCategorie: 'Categories',
   listType: 'Types',
   detailPage: 'Details',
   detailEntete: 'Details_Entete',
   about: 'About',
   doleance: 'Doleance',
   downloadData: 'DownloadData',
   importedData: 'ImportedData',
   information: 'Information',
};
